# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://www.understandingdata.net/"
title = "Understanding Data"
languageCode = "en-EN"
copyright = "(c) 2017 Rose Hartman"
theme = "hyde"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "yaml"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    category = "categories"

[author]
    name = "Rose Hartman, PhD"
    email = "rose@understandingdata.net"   

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    Description = "Professional Statistical Consulting"
    
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "Professional Statistical Consulting"
    defaultKeywords = "data, analysis, consulting, research"

    # Hide estimated reading time for posts.
    # Default (if omitted) is false.
    hideReadingTime = false

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    # theme = "theme-base-08"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Optional additional custom CSS file URL, will override other styles.
    customCSS = ""

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Professional Statistical Consulting"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Home"

    # Metadata used to drive integrations.
    googleAnalytics = "UA-96182710-1"
    gravatarHash = ""

    # Sidebar social links, these must be full URLs.
    github = "rosemm/rexamples"
    bitbucket = ""
    stackOverflow = ""
    linkedin = "rose-maier-hartman-phd-97387113b"
    googleplus = ""
    facebook = ""
    twitter = ""
    youtube = ""

    # Other social-like sidebar links
    rss = false  # switch to true to enable RSS icon link
    flattr = ""  # populate with your flattr uid