---
Title: Mapping prenatal care utilization in Chicago
Date: 2018-03-03
Category: Visualization
tags: [ "maps", "ggplot2", "R", "city-of-chicago", "tidyverse"]
Draft: true
output: 
  md_document: 
    preserve_yaml: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

The geographical information for neighborhoods can be downloaded [via the City of Chicago data portal](https://data.cityofchicago.org/api/geospatial/cauq-8yn6?method=export&format=Shapefile). This is called a "shapefile". Download it, and unzip it in the current working directory.

description

<!--more-->

<h3 id="mapping libraries">
Mappping libraries in R
</h3>

```{r}
library("rgeos") # has geographical information maptools will use
library("rgdal") # can read the shapefile
library("maptools") # has map data that ggplot2 can use to draw maps
library("ggplot2") # lovely, general-purpose plotting library
```

```{r}
map <- rgdal::readOGR(dsn="./Boundaries - Community Areas (current)", layer="geo_export_eebaa6ac-ecef-4bac-905c-ac8060d2bc7a") # . is current working directory

summary(map) # check out this object

head(slot(map, "data")) # a dataframe that's part of the map object
```

```{r}
library(tidyverse)
library(broom)
map_df <- tidy(map, region = "community") %>% # turns the spatial data into a more useable dataframe
# for specific info on the region argument, see ?sp_tidiers
  as.tbl() # for tidy printing

print(map_df) # check out this dataframe
```

```{r}
# to convert community names to sentence case instead of all caps
capwords <- function(s) {
    cap <- function(s) paste(toupper(substring(s, 1, 1)), tolower(substring(s, 2)),
                             sep = "", collapse = " " )
    sapply(strsplit(s, split = " "), cap, USE.NAMES = !is.null(names(s)))
}
map_df$id <- capwords(map_df$id)
```

```{r}
# save code for a base map with theme, etc. fixed up
base_map <- function(df){
  ggplot(df, aes(x=long, y=lat, group = group)) + 
  # draw neighborhood shapes  
  geom_polygon() + 
  theme_classic() + 
  # controls the aspect ratio
  coord_fixed(1.3) + 
  # removes the axes
  theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
  )
}
# a basic map showing just the shape of each neighborhood
base_map(map_df) 
```

Now to connect data on prenatal care to the geographical data about neighborhoods so we can map it!

```{r}
library(readr)
data1 <- read_csv("/Users/TARDIS/Dropbox (Personal)/understandingdata/content/post/chicago_prenatal_care.csv")
data2 <- read_csv("/Users/TARDIS/Dropbox (Personal)/understandingdata/content/post/chicago_prenatal_care_adequate.csv")
```

```{r}
# ?select_if

# checks to see if there are any non-missing cases in a vector
not_all_missing <- function(x) !all(is.na(x))

# combine the data together into one dataframe
prenatal_data <- dplyr::full_join(data1, data2) %>% 
  # drop empty variables
  dplyr::select_if(not_all_missing) %>% 
  # extract community from Geo_Group variable
  tidyr::extract(Geo_Group, "community", regex = "[[:digit:]]+[-]([^[:digit:]]+)")

# drop cases that aren't about a specific neightboorhood (the data includes general Chicago info as well)
community_data <- prenatal_data %>% 
  dplyr::filter(Geography == "Community Area") 
chicago_data <- prenatal_data %>% 
  dplyr::filter(Geography == "City") 
```

```{r eda}
table(community_data$Indicator) # the two indicators we have here
table(community_data$Year) # all data are pooled from 2010-2014

# see the distribution of percents for each of the indicators
ggplot(community_data, aes(x=Percent)) + 
  geom_histogram(bins = 20) + 
  facet_wrap(~Indicator) + 
  theme_classic()

community_data %>% 
  group_by(Indicator) %>% 
  summarize(min_Perc = min(Percent),
            mean_Perc = mean(Percent),
            median_Perc = median(Percent),
            max_Perc = max(Percent)) 
```
```{r}
prenatal_percents <- community_data %>% 
  dplyr::select(Indicator, community, Percent)

# add the percent info to the map_df
combined_df <- full_join(map_df, prenatal_percents, by = c("id" = "community"))

# check communities that didn't join cleanly
combined_df %>% 
  dplyr::filter(is.na(Indicator) | is.na(group)) %>% 
  dplyr::select(group, id) %>% 
  unique()

# Ah, spelling differences. :) Let's correct those.
map_df$id <- gsub(x=map_df$id, pattern = "Lake View", replacement = "Lakeview")
map_df$id <- gsub(x=map_df$id, pattern = "Mckinley Park", replacement = "McKinley Park")
map_df$id <- gsub(x=map_df$id, pattern = "Ohare", replacement = "O'Hare")

# re-run the join
combined_df <- full_join(map_df, prenatal_percents, by = c("id" = "community"))
```

```{r mapping_prenatal_care}
base_map(combined_df) + 
  # draw the neighborhod shapes
  geom_polygon(aes(fill = Percent)) + 
  # add an outline around each neighborhood
  geom_path(color = "black") + 
  facet_wrap(~Indicator) + 
  # control the colors for the low and high ends of the Percent scale
  scale_fill_continuous(low = "darkred", high = "white")
```

```{r city_plots}
# a function for getting boxplots by Demography
boxplots <- function(df, Demography){
  ggplot(df, aes(y=Percent, x = Demo_Group, fill = Demo_Group)) + 
  geom_boxplot() + 
  facet_wrap(~Indicator, ncol = 1) + 
  theme_classic() + 
  labs(fill = Demography, x = NULL) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
}

# a function for getting lines over time by Demography
lines_over_time <- function(df, Demography){
  ggplot(df, aes(x=Year, y=Percent, group = Demo_Group, color = Demo_Group)) + 
  geom_line() + 
  facet_wrap(~Indicator, ncol = 1) + 
  theme_classic() +
  labs(color = Demography) 
}

# get both plots at once
boxplots_and_lines <-function(df, Demography, save_dir = NULL){
  p1 <- boxplots(df, Demography)
  p2 <- lines_over_time(df, Demography)
  print(p1)
  print(p2)
  # option to save the plots
  if(!is.null(save_dir)){
    dir.create(file.path(save_dir), showWarnings = FALSE) # if no save_dir folder exists, create it
    ggsave(paste0(Demography, "_Boxplots.png"), 
           plot = p1, 
           path = save_dir,
           width = 4, height = 7, units = "in")
    ggsave(paste0(Demography, "_Lines.png"), 
           plot = p2, 
           path = save_dir,
           width = 4, height = 7, units = "in")
  }
}

chicago_data %>% 
  dplyr::filter(Demography == "Age") %>% 
  boxplots_and_lines("Age")

chicago_data %>% 
  dplyr::filter(Demography == "Economic Hardship") %>% 
  # make hardship a factor, to control the plotting order
  dplyr::mutate(Demo_Group = factor(Demo_Group, levels = c("High", "Medium", "Low"), ordered = TRUE)) %>% 
  boxplots_and_lines("Economic Hardship")

chicago_data %>% 
  dplyr::filter(Demography == "Race-ethnicity") %>% 
  # drop the category that pools it all together
  dplyr::filter(Demo_Group != "All race-ethnicities") %>% 
  # add a line break (\n) in long race-ethnicity names
  dplyr::mutate(Demo_Group = gsub(x=Demo_Group, pattern = "Non-Hispanic", replacement = "Non-Hispanic\n")) %>% 
  boxplots_and_lines("Race-ethnicity")
```



<h3 id="further reading">
Further reading
</h3>
[https://mgimond.github.io/Spatial/data-manipulation-in-r.html](https://mgimond.github.io/Spatial/data-manipulation-in-r.html)

[http://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html](http://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html)
